import 'package:flutter/foundation.dart';

import 'practice_difficulty.dart';
import 'practice_figure.dart';
import 'practice_skill.dart';
import 'practice_topic.dart';

/// How a practice question is answered. New types slot in without touching the
/// session flow (the UI switches on this).
enum PracticeQuestionType {
  /// Pick one of several choices.
  multipleChoice,

  /// Pick true or false.
  trueFalse,

  /// Type a short answer (number / word).
  input,

  /// Solve for a variable and type the value.
  equation,
}

/// One selectable choice in a multiple-choice / true-false question.
@immutable
class PracticeOption {
  const PracticeOption(this.text, {this.isCorrect = false});

  final String text;
  final bool isCorrect;
}

/// A single interactive practice question.
///
/// Choice questions ([multipleChoice] / [trueFalse]) use [options]; typed
/// questions ([input] / [equation]) validate against [acceptedAnswers].
@immutable
class PracticeQuestion {
  const PracticeQuestion({
    required this.id,
    required this.topic,
    required this.difficulty,
    required this.type,
    required this.prompt,
    required this.explanation,
    this.promptLatex,
    this.spokenPrompt,
    this.options = const [],
    this.acceptedAnswers = const [],
    this.skillId,
    this.figure,
    this.subtopic,
    this.estimatedSteps,
    this.estimatedSolveTimeSeconds,
    this.gradeLevel,
  });

  final String id;
  final PracticeTopic topic;
  final PracticeDifficulty difficulty;
  final PracticeQuestionType type;

  /// The [PracticeSkill.id] this question exercises, when generated by the
  /// Stage 15 engine. Drives per-skill mastery attribution + the anti-repetition
  /// fingerprint; `null` for legacy / hand-authored bank questions (they simply
  /// don't feed the per-skill model).
  final String? skillId;

  /// Plain-language instruction, e.g. "Solve for x".
  final String prompt;

  /// Optional LaTeX shown large under the prompt (e.g. `2x + 5 = 13`).
  final String? promptLatex;

  /// Optional plain-text reading of [promptLatex] for screen readers, used when
  /// the LaTeX contains commands (e.g. \frac) that would otherwise be announced
  /// as raw markup.
  final String? spokenPrompt;

  /// Choices for [multipleChoice] / [trueFalse].
  final List<PracticeOption> options;

  /// Accepted normalized answers for [input] / [equation].
  final List<String> acceptedAnswers;

  /// Shown after the student answers — the "why".
  final String explanation;

  /// Optional geometry figure rendered above the prompt (Stage 3+). Built by a
  /// rule template from its own verified numbers, so it's correct by
  /// construction. `null` for every non-figure question (the vast majority).
  final PracticeFigure? figure;

  // ---- Difficulty metadata (stored with every generated question) ----
  // Additive, all optional; the getters below fall back to the difficulty's
  // [DifficultySpec] so a question always exposes complete metadata even when a
  // generator didn't stamp explicit values. Powers XP balancing, leaderboards,
  // daily challenges, analytics and adaptive recommendations.

  /// The fine-grained concept, e.g. the [PracticeSkill.label] ("Quadratics").
  final String? subtopic;

  /// Measured/estimated solving steps for THIS question. Falls back to the
  /// level's target when a generator didn't count them ([steps]).
  final int? estimatedSteps;

  /// Estimated solve-time budget in seconds ([solveTimeSeconds] getter).
  final int? estimatedSolveTimeSeconds;

  /// Grade band, e.g. "A-Level". Falls back to the level's [gradeLabel] ([grade]).
  final String? gradeLevel;

  /// Solving steps, backed by the difficulty spec's target when unset.
  int get steps => estimatedSteps ?? difficulty.spec.targetSteps;

  /// Solve-time budget in seconds, backed by the difficulty spec when unset.
  int get solveTimeSeconds =>
      estimatedSolveTimeSeconds ?? difficulty.spec.estimatedSolveTimeSeconds;

  /// Grade band, backed by the difficulty spec's grade label when unset.
  String get grade => gradeLevel ?? difficulty.spec.gradeLabel;

  /// The fine-grained concept label, backed by the skill's label when unset.
  String? get subtopicLabel =>
      subtopic ?? PracticeSkill.byId(skillId)?.label;

  /// A clone with a different [id] — used by the engine to stamp a unique
  /// per-slot id onto a cached / reused question.
  PracticeQuestion withId(String id) => PracticeQuestion(
        id: id,
        topic: topic,
        difficulty: difficulty,
        type: type,
        prompt: prompt,
        explanation: explanation,
        promptLatex: promptLatex,
        spokenPrompt: spokenPrompt,
        options: options,
        acceptedAnswers: acceptedAnswers,
        skillId: skillId,
        // TRAP: withId() hand-copies every field. Omitting `figure` here would
        // SILENTLY drop the figure at slot-restamp (adaptive_practice_service
        // stamps every generated question via .withId(slotId)) — no error, no
        // log, figures just never appear. Covered by a survives-restamp test.
        figure: figure,
        // Same trap for the difficulty metadata — must be re-copied here or it
        // silently vanishes on restamp (survives-restamp test covers these too).
        subtopic: subtopic,
        estimatedSteps: estimatedSteps,
        estimatedSolveTimeSeconds: estimatedSolveTimeSeconds,
        gradeLevel: gradeLevel,
      );

  int get xpReward => difficulty.baseXp;

  int get correctOptionIndex => options.indexWhere((o) => o.isCorrect);

  /// The canonical correct answer as display text (for the feedback panel).
  String get correctAnswerText {
    if (options.isNotEmpty) {
      final index = correctOptionIndex;
      return index >= 0 ? options[index].text : '';
    }
    return acceptedAnswers.isNotEmpty ? acceptedAnswers.first : '';
  }

  /// Evaluates a submitted answer (an option's text, or typed input).
  bool evaluate(String submitted) {
    if (options.isNotEmpty) {
      final index = correctOptionIndex;
      if (index < 0) return false;
      return _normalize(submitted) == _normalize(options[index].text);
    }
    final normalized = _normalizeMath(submitted);
    if (normalized.isEmpty) return false;
    return acceptedAnswers.any((a) => _normalizeMath(a) == normalized);
  }

  static String _normalize(String s) => s.trim().toLowerCase();

  /// Normalizes a math answer: lowercases, strips whitespace + currency/grouping
  /// symbols, and drops a leading assignment so "x = 4", "$4" and "4" all
  /// compare as "4".
  static String _normalizeMath(String s) {
    var value =
        s.trim().toLowerCase().replaceAll(RegExp(r'[\s$,£€]'), '');
    final eq = value.indexOf('=');
    if (eq >= 0) value = value.substring(eq + 1);
    return value;
  }
}
